### ISSUE TITLE
Card form

### ISSUE THREAD

**Issue by badabam** [neuefische/todo-app#2]
*As a* user
*I want to* have a card form 
*so that* I can create new cards

### Acceptance criteria
- [ ] Has title, content and tags
- [ ] title and content are text
- [ ] tags is an optional list of text
- [ ] it can only be sent, if content and title is filled out
- [ ] after being sent, the form is cleared
- [ ] ...

### Tasks
- [ ] Create Form component
- [ ] Add styling
- [ ] Add component to docz
- [ ] Add integration test

### Limitations
- No backend, just update the state
